name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node & Yarn 4
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Enable Corepack & install deps
        run: |
          corepack enable
          yarn install --immutable

      - name: Build the static site
        run: yarn build         # outputs to ./build

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build           # must match output dir

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4