# .github/workflows/deploy.yml
name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: [main]        # redeploy every push to main
  workflow_dispatch:        # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out repository
      - uses: actions/checkout@v4

      # 2. Install Node
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Activate Yarn 4
      - name: Activate Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version

      # 4. Try immutable install, fallback if needed
      - name: Install dependencies (try immutable)
        run: |
          yarn install --immutable || (
            echo "⚠️ Lockfile mismatch — falling back to normal install"
            yarn install
          )

      # 5. Generate SvelteKit types
      - name: Generate SvelteKit types
        run: yarn svelte-kit sync

      # 6. Build the static site
      - name: Build the site
        run: yarn build

      # 7. Upload build/ as the Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4