name: Deploy SvelteKit to GitHub Pages

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out the repo
      - uses: actions/checkout@v4

      # 2. Install Node 20 (no yarn cache flag!)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. Activate Yarn 4 via Corepack
      - name: Enable Corepack & Yarn 4
        run: |
          corepack enable
          corepack prepare yarn@4.9.2 --activate
          yarn --version          # should print 4.9.2

      # 4. Install dependencies
      - name: Install dependencies
        run: yarn install --immutable

      # 5. Build the static site (adapter-static -> ./build)
      - name: Build the site
        run: yarn build

      # 6. Upload build/ as the Pages artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4